server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/feedback_db
    # url: jdbc:postgresql://postgres-feedback-db:5432/feedback_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/
