server:
  port: 8087

spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.trusted.packages: "*"
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: kafka:9092
      rabbit:
        binder:
          addresses: rabbitmq:5672
      bindings:
        user-events-in:
          destination: user-events
          group: notification-service
          binder: kafka
        enrollment-events-in:
          destination: enrollment-events
          group: notification-service
          binder: kafka
        feedback-events-in:
          destination: feedback-events
          group: notification-service
          binder: kafka
        springCloudBusInput:
          binder: rabbit
        springCloudBusOutput:
          binder: rabbit
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
        
topics:
  user-registered: ${TOPIC_USER_REGISTERED:user-events}
  enrollment-created: ${TOPIC_ENROLLMENT_CREATED:enrollment-events}
  feedback-created: ${TOPIC_FEEDBACK_CREATED:feedback-events}

auth:
  jwt:
    secretKey: ${JWT_SECRET:defaultSecretKey}
    expirationDays: ${JWT_EXPIRATION_DAYS:30}
    issuer: karate-management-system-backend

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    mail:
      enabled: false
  endpoint:
    refresh:
      enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 0.1   # PROD: tylko część requestów
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

logging:
  level:
    root: INFO
    com.karate: INFO

app:
  web:
    base-url: ${APP_WEB_BASE_URL:http://localhost:3000}
    dashboard-url: ${APP_WEB_DASHBOARD_URL:${app.web.base-url}/app/dashboard}
    preferences-url: ${APP_WEB_PREFERENCES_URL:${app.web.base-url}/settings/notifications}
    privacy-url: ${APP_WEB_PRIVACY_URL:${app.web.base-url}/settings/security}
