server:
  port: 8087

spring:
    rabbitmq:
    host: localhost
    #    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
            default-binder: rabbit
      bindings:
        user-events-in:
          destination: user-events
          group: notification-service
          binder: kafka
        enrollment-events-in:
          destination: enrollment-events
          group: notification-service
          binder: kafka
        feedback-events-in:
          destination: feedback-events
          group: notification-service
          binder: kafka
auth:
  jwt:
    secretKey: ${JWT_SECRET:defaultSecretKey}
    expirationDays: ${JWT_EXPIRATION_DAYS:30}
    issuer: karate-management-system-backend

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      # defaultZone: http://service-registry:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
  endpoint:
    refresh:
      enabled: true
